sudo: true

language: python

services:
- docker

addons:
  apt:
    packages:
    - qemu-user-static

before_install:
- docker build -t chukysoria/spotify-connect-web -f Dockerfile .

install: true

script:
- docker run -v $TRAVIS_BUILD_DIR:/usr/src/app -e TOX_ENV=$TOX_ENV
  chukysoria/spotify-connect-web -c 'py.test'

after_success:
- docker run -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_BRANCH=$TRAVIS_BRANCH
  -v $TRAVIS_BUILD_DIR:/usr/src/app chukysoria/spotify-connect-web -c
  coveralls
