sudo: true

language: python

services:
- docker

cache:
- pip

env:
- TOX_ENV=py27
- TOX_ENV=py34
- TOX_ENV=pypy
- TOX_ENV=flake8

addons:
  apt:
    packages:
    - qemu-user-static
    - pandoc

before_install:
- docker build -t chukysoria/spotify-connect-web -f Dockerfile .

install:
- pip install pypandoc

script:
- docker run -v $TRAVIS_BUILD_DIR:/usr/src/app -e TOX_ENV=$TOX_ENV chukysoria/spotify-connect-web
  -c 'tox -e $TOX_ENV'

after_success:
- docker run -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_BRANCH=$TRAVIS_BRANCH
  -v $TRAVIS_BUILD_DIR:/usr/src/app chukysoria/spotify-connect-web -c coveralls

before_deploy:
- sudo chown -R $USER $TRAVIS_BUILD_DIR

deploy:
- provider: pypi
  user: chukysoria
  password:
    secure: TAlHHnijUjVSbz5Vw9z1xucBlz2eaQwHejf2vKQfeT7L6XqlGgnhnHVhwaIQBA4kyWxLtI3/jnKEeGNUW+wKxhEBKbleBraZMtaiEW9MFqkRlYa2/TSk2F2tskEyudp24fLcOnpx0ErQ1bnH3vd6Erqdilv2zrPA9QdwA9QgBG3hoXRYZvFsP97BFJlxIAzQhMOD4ykhgVBKHZQSX6ioxKO6K/Yjhb9s+OWl9Ltz7MgAyb+SdGCnDpG1QT9WXqpgQnWFZ8QcorkhQII/BIaKeh9Nx654ifruXOpoieUkRFLnnBW+OmMvIGjYgxhxIkXl45NypqvYXIh7xknLQeiOJT03FUkkK1QlOeY2iAQfj3MjCMFldksbNNitLuVm+TdiU7s7C4E/bs8NMyvpzT5VSzOTwlKqZXt/f6Kb1nVzTj+bJaM4pzyWwrxhxYr6XJ02be15C8LUDmFfiwhQRelp0nftSFwSrpNSWe1CN94bnA5Pn/B3mof40Fujldb2bQ8a69Jb3V33n/YqiKhwyF2Yh1LDV30za9PL9de8C4MT1qMvulC2j2RPY2Ne5/UbblIqB4ihXu8dKdwhyhS/A8RBvHY1zQeJGJBIA/0IJY0mxNxRJgJkZMNzQ6W3TllCjUSI8KkQRxm7XVGVw8USmLJkuMwJWufvog/78XTdsAEDh1M=
  on:
    tags: true
    condition: "$TOX_ENV = py27"
    distributions: sdist bdist_wheel
    repo: chukysoria/spotify-connect-web
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: chukysoria
  password:
    secure: TAlHHnijUjVSbz5Vw9z1xucBlz2eaQwHejf2vKQfeT7L6XqlGgnhnHVhwaIQBA4kyWxLtI3/jnKEeGNUW+wKxhEBKbleBraZMtaiEW9MFqkRlYa2/TSk2F2tskEyudp24fLcOnpx0ErQ1bnH3vd6Erqdilv2zrPA9QdwA9QgBG3hoXRYZvFsP97BFJlxIAzQhMOD4ykhgVBKHZQSX6ioxKO6K/Yjhb9s+OWl9Ltz7MgAyb+SdGCnDpG1QT9WXqpgQnWFZ8QcorkhQII/BIaKeh9Nx654ifruXOpoieUkRFLnnBW+OmMvIGjYgxhxIkXl45NypqvYXIh7xknLQeiOJT03FUkkK1QlOeY2iAQfj3MjCMFldksbNNitLuVm+TdiU7s7C4E/bs8NMyvpzT5VSzOTwlKqZXt/f6Kb1nVzTj+bJaM4pzyWwrxhxYr6XJ02be15C8LUDmFfiwhQRelp0nftSFwSrpNSWe1CN94bnA5Pn/B3mof40Fujldb2bQ8a69Jb3V33n/YqiKhwyF2Yh1LDV30za9PL9de8C4MT1qMvulC2j2RPY2Ne5/UbblIqB4ihXu8dKdwhyhS/A8RBvHY1zQeJGJBIA/0IJY0mxNxRJgJkZMNzQ6W3TllCjUSI8KkQRxm7XVGVw8USmLJkuMwJWufvog/78XTdsAEDh1M=
  on:
    all_branches: true
    condition: "$TOX_ENV = py27"
    distributions: "sdist bdist_wheel"
    repo: chukysoria/spotify-connect-web