FROM chukysoria/rpi-python-testing:armv7
MAINTAINER Carlos Sánchez

WORKDIR /usr/src/app

RUN [ "cross-build-start" ]

RUN pip install coveralls tox

ENTRYPOINT [ "/bin/bash" ]

RUN [ "cross-build-end" ]
