FROM chukysoria/rpi-python-testing:armv7
MAINTAINER Carlos Sánchez

WORKDIR /usr/src/app

RUN [ "cross-build-start" ]

ADD https://github.com/sashahilton00/spotify-connect-resources/raw/master/libs/armhf/armv7/release-esdk-1.20.0-v1.20.0-g594175d4/libspotify_embedded_shared.so /usr/lib/
COPY ./dev-requirements.txt /usr/src/app/dev-requirements.txt
RUN pip install -r dev-requirements.txt

ENTRYPOINT [ "/bin/bash" ]

RUN [ "cross-build-end" ]

EXPOSE 4000
